### ISSUE TITLE
perl-scripts in AFDKO

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/perl-scripts#2]
@ Ken Lunde

The perl-scripts are also contained in the AFDKO. I propose to either remove them from the AFDKO or, better, to integrate the perl-scripts repository into the AFDKO.

**Comment by kenlunde** [comment]
What is in [AFDKO](https://github.com/adobe-type-tools/afdko/tree/master/afdko/Tools/SharedData/FDKScripts) is a subset of what is provided here, and my personal preference would be to remove the corresponding scripts from that project, and add a pointer to this project in that project's _README.md_ file. I feel that this is the better way to make sure that the latest versions are being used, as I am the sole maintainer of this project and the author of the Perl scripts that it provides.

**Comment by kenlunde** [comment]
I'd like to get @readroberts' opinion about this.

**Comment by readroberts** [comment]
Sounds like a good idea to me. Let's do it.

**Comment by Arno-Enslin** [comment]
> and add a pointer to this project in that project's README.md file

And to the [FDK build notes. ](https://raw.githubusercontent.com/adobe-type-tools/afdko/master/FDK/FDK%20Build%20Notes.txt) The (latest versions of the) scripts should remain in the prebuilt releases.

**Comment by kenlunde** [comment]
The Perl scripts in [AFDKO](https://github.com/adobe-type-tools/afdko/tree/master/afdko/Tools/SharedData/FDKScripts) have been removed, so I am closing this issue.
